name: emulators
description: A utility library to automate mobile emulators. Wraps `xcrun` for iOS and the Android CLI tools.
version: 0.4.9
repository: https://github.com/tim-smart/dart_emulators.git

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  fpdt: ^0.0.59
  freezed_annotation: ^2.0.1
  json_annotation: ^4.5.0
  path: ^1.8.1

dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^1.0.4
  freezed: ^2.0.2
  json_serializable: ^6.2.0
